### ISSUE TITLE
PDF rendering artifacts.

### ISSUE THREAD

**Issue by MicahZoltu** [seresistvanandras/MixEth#1]
I have no idea what the cause is, but https://github.com/seresistvanandras/MixEth/blob/master/article/main.pdf appears to have a bunch of rendering artifacts that make it uncomfortable to read.  Nothing critical, just straining on the eyes.  This may just be a problem of needing to render the PDF with less compression or something?  If I didn't know any better, I would say that this is a scan of a printed paper.

**Comment by seresistvanandras** [comment]
Thanks Micah! Hmm maybe I should update my TexStudio from 2.10.8.? Or do you think it is the font style which is straining on the eyes? Honestly I have not got any idea neither! Anyway thanks again. I will look into this.

**Comment by MicahZoltu** [comment]
I'm not sure what is causing it, but the characters are not crisp, some of them have stray lines (artifacts), like you would see if you scanned an old document on an old scanner.  It is really bizarre to see that in something that is a digital rendering... it doesn't really make sense other than perhaps bad compression or something?

I may expect similar artifacts if I took a screenshot of some rendered text and then compressed it (lossy) and then turned that file into a PDF?

**Comment by MicahZoltu** [comment]
![image](https://user-images.githubusercontent.com/886059/47073879-d132e380-d22b-11e8-9d4c-4a1c9ef1ad7b.png)
Here is an example of what I'm seeing.  Notice the artifacts after each of the `h` characters, as well as some around the `w` and `r`.  Each zoom level with my PDF viewer results in a different set of artifacts, but I can't find a zoom level that is artifact free.  On my fairly large monitor, if I do one full page the text appears blurry overall with a mix of artifacts. If I zoom way in (like in that screenshot) it is fairly crisp, but ends up with more of those artifacts that cause it to be straining on the eyes for that reason instead of for being blurry.

I wish I could offer more useful feedback than "it is straining on the eyes for some reason I can't explain"!
